# Generated by Django 3.2.5 on 2021-08-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_note_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='modified_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
